// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for
/// [Operations.ListOperations][google.longrunning.Operations.ListOperations].
///
/// [google.longrunning.Operations.ListOperations]: <doc:Operations/listOperations(request:)>
public struct ListOperationsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the operation's parent resource.
  public var name: String

  /// The standard list filter.
  public var filter: String

  /// The standard list page size.
  public var pageSize: Int32

  /// The standard list page token.
  public var pageToken: String

  /// When set to `true`, operations that are reachable are returned as normal,
  /// and those that are unreachable are returned in the
  /// [ListOperationsResponse.unreachable] field.
  ///
  /// This can only be `true` when reading across collections e.g. when `parent`
  /// is set to `"projects/example/locations/-"`.
  ///
  /// This field is not by default supported and will result in an
  /// `UNIMPLEMENTED` error if set unless explicitly documented otherwise in
  /// service or product specific documentation.
  public var returnPartialSuccess: Bool

  /// Initialize a new instance of `ListOperationsRequest`.
  public init(
    name: String = String(),
    filter: String = String(),
    pageSize: Int32 = Int32(),
    pageToken: String = String(),
    returnPartialSuccess: Bool = Bool(),
  ) {
    self.name = name
    self.filter = filter
    self.pageSize = pageSize
    self.pageToken = pageToken
    self.returnPartialSuccess = returnPartialSuccess
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.longrunning.ListOperationsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
