// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax

import GoogleCloudWkt
import GoogleRpc

/// Manages long-running operations with an API service.
///
/// When an API method normally takes long time to complete, it can be designed
/// to return [Operation][google.longrunning.Operation] to the client, and the
/// client can use this interface to receive the real response asynchronously by
/// polling the operation resource, or pass the operation resource to another API
/// (such as Pub/Sub API) to receive the response.  Any API service that returns
/// long-running operations should implement the `Operations` interface so
/// developers can have a consistent client experience.
///
/// [google.longrunning.Operation]: <doc:Operation>
///
/// @Snippet(path: "OperationsQuickstart")
public protocol Operations {
  /// Lists operations that match the specified filter in the request. If the
  /// server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws -> ListOperationsResponse

  /// Gets the latest state of a long-running operation.  Clients can use this
  /// method to poll the operation result at intervals as recommended by the API
  /// service.
  ///
  /// @Snippet(path: "Operations_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> Operation

  /// Deletes a long-running operation. This method indicates that the client is
  /// no longer interested in the operation result. It does not cancel the
  /// operation. If the server doesn't support this method, it returns
  /// `google.rpc.Code.UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Starts asynchronous cancellation on a long-running operation.  The server
  /// makes a best effort to cancel the operation, but success is not
  /// guaranteed.  If the server doesn't support this method, it returns
  /// `google.rpc.Code.UNIMPLEMENTED`.  Clients can use
  /// [Operations.GetOperation][google.longrunning.Operations.GetOperation] or
  /// other methods to check whether the cancellation succeeded or whether the
  /// operation completed despite cancellation. On successful cancellation,
  /// the operation is not deleted; instead, it becomes an operation with
  /// an [Operation.error][google.longrunning.Operation.error] value with a
  /// [google.rpc.Status.code][google.rpc.Status.code] of `1`, corresponding to
  /// `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: <doc:Operation/error>
  /// [google.longrunning.Operations.GetOperation]: <doc:Operations/getOperation(request:)>
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  ///
  /// @Snippet(path: "Operations_CancelOperation")
  func cancelOperation(request: CancelOperationRequest) async throws

  /// Lists operations that match the specified filter in the request. If the
  /// server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListOperationsResponse

  /// Gets the latest state of a long-running operation.  Clients can use this
  /// method to poll the operation result at intervals as recommended by the API
  /// service.
  ///
  /// @Snippet(path: "Operations_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation

  /// Deletes a long-running operation. This method indicates that the client is
  /// no longer interested in the operation result. It does not cancel the
  /// operation. If the server doesn't support this method, it returns
  /// `google.rpc.Code.UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Starts asynchronous cancellation on a long-running operation.  The server
  /// makes a best effort to cancel the operation, but success is not
  /// guaranteed.  If the server doesn't support this method, it returns
  /// `google.rpc.Code.UNIMPLEMENTED`.  Clients can use
  /// [Operations.GetOperation][google.longrunning.Operations.GetOperation] or
  /// other methods to check whether the cancellation succeeded or whether the
  /// operation completed despite cancellation. On successful cancellation,
  /// the operation is not deleted; instead, it becomes an operation with
  /// an [Operation.error][google.longrunning.Operation.error] value with a
  /// [google.rpc.Status.code][google.rpc.Status.code] of `1`, corresponding to
  /// `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: <doc:Operation/error>
  /// [google.longrunning.Operations.GetOperation]: <doc:Operations/getOperation(request:)>
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  ///
  /// @Snippet(path: "Operations_CancelOperation")
  func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
}

extension Clients {
  /// The recommended implementation for ``Operations``.
  public class OperationsClient: Operations {
    let inner: GoogleCloudGax.HTTPClient

    /// Creates a new `OperationsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://longrunning.googleapis.com")
    }

    /// See `Operations.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListOperationsResponse {
      let path = try { () throws -> String in
        guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(request.returnPartialSuccess, prefix: "returnPartialSuccess")
      )
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, response) = try await self.inner.data(for: req)
      if !(200..<300).contains(response.statusCode) {
        throw GoogleCloudGax.RequestError.http(
          GoogleCloudGax.HTTPDetails(
            http_status_code: response.statusCode,
            headers: [:],
            payload: data,
          ))
      }
      return try GoogleCloudGax.ProtoJSONDecoder().decode(ListOperationsResponse.self, from: data)
    }

    /// Lists operations that match the specified filter in the request. If the
    /// server doesn't support this method, it returns `UNIMPLEMENTED`.
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> some AsyncSequence<Operation, Error> {
      let listRpc = { (token: String) async throws -> ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Operations.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Operation {
      let path = try { () throws -> String in
        guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      let (data, response) = try await self.inner.data(for: req)
      if !(200..<300).contains(response.statusCode) {
        throw GoogleCloudGax.RequestError.http(
          GoogleCloudGax.HTTPDetails(
            http_status_code: response.statusCode,
            headers: [:],
            payload: data,
          ))
      }
      return try GoogleCloudGax.ProtoJSONDecoder().decode(Operation.self, from: data)
    }

    /// See `Operations.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> String in
        guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      let (data, response) = try await self.inner.data(for: req)
      if !(200..<300).contains(response.statusCode) {
        throw GoogleCloudGax.RequestError.http(
          GoogleCloudGax.HTTPDetails(
            http_status_code: response.statusCode,
            headers: [:],
            payload: data,
          ))
      }
    }

    /// See `Operations.cancelOperation`
    public func cancelOperation(
      request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> String in
        guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):cancel"
      }()
      let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, response) = try await self.inner.data(for: req)
      if !(200..<300).contains(response.statusCode) {
        throw GoogleCloudGax.RequestError.http(
          GoogleCloudGax.HTTPDetails(
            http_status_code: response.statusCode,
            headers: [:],
            payload: data,
          ))
      }
    }
  }
}

// Default implementations
extension Operations {
  public func listOperations(request: ListOperationsRequest) async throws -> ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(byItem: ListOperationsRequest) throws -> some AsyncSequence<
    Operation, Error
  > {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> some AsyncSequence<Operation, Error> {
    let listRpc = { (token: String) async throws -> ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> Operation {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(request: CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
