// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Manages long-running operations with an API service.
///
/// When an API method normally takes long time to complete, it can be designed
/// to return [Operation][google.longrunning.Operation] to the client, and the
/// client can use this interface to receive the real response asynchronously by
/// polling the operation resource, or pass the operation resource to another API
/// (such as Pub/Sub API) to receive the response.  Any API service that returns
/// long-running operations should implement the `Operations` interface so
/// developers can have a consistent client experience.
///
/// [google.longrunning.Operation]: <doc:Operation>
///
/// @Snippet(path: "OperationsQuickstart")
public class OperationsClient: Clients.OperationsProtocol {
  let inner: any Clients.OperationsStub

  /// Creates a new `OperationsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.OperationsStub = try Clients.OperationsTransport(options)
    inner = Clients.OperationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OperationsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists operations that match the specified filter in the request. If the
  /// server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_ListOperations")
  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Lists operations that match the specified filter in the request. If the
  /// server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_ListOperations")
  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the latest state of a long-running operation.  Clients can use this
  /// method to poll the operation result at intervals as recommended by the API
  /// service.
  ///
  /// @Snippet(path: "Operations_GetOperation")
  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Deletes a long-running operation. This method indicates that the client is
  /// no longer interested in the operation result. It does not cancel the
  /// operation. If the server doesn't support this method, it returns
  /// `google.rpc.Code.UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Operations_DeleteOperation")
  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Starts asynchronous cancellation on a long-running operation.  The server
  /// makes a best effort to cancel the operation, but success is not
  /// guaranteed.  If the server doesn't support this method, it returns
  /// `google.rpc.Code.UNIMPLEMENTED`.  Clients can use
  /// [Operations.GetOperation][google.longrunning.Operations.GetOperation] or
  /// other methods to check whether the cancellation succeeded or whether the
  /// operation completed despite cancellation. On successful cancellation,
  /// the operation is not deleted; instead, it becomes an operation with
  /// an [Operation.error][google.longrunning.Operation.error] value with a
  /// [google.rpc.Status.code][google.rpc.Status.code] of `1`, corresponding to
  /// `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: <doc:Operation/error>
  /// [google.longrunning.Operations.GetOperation]: <doc:Operations/getOperation(request:)>
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  ///
  /// @Snippet(path: "Operations_CancelOperation")
  public func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OperationsClient`.
  ///
  /// To mock `OperationsClient` change your functions to receive
  /// `some OperationsProtocol` or `any OperationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OperationsProtocol {
    /// See `OperationsClient.listOperations`.
    func listOperations(request: ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `OperationsClient.listOperations`.
    func listOperations(
      byItem: ListOperationsRequest
    ) throws -> any AsyncSequence<Operation, Swift.Error>

    /// See `OperationsClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<Operation, Swift.Error>

    /// See `OperationsClient.getOperation`.
    func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

    /// See `OperationsClient.getOperation`.
    func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongrunning.Operation

    /// See `OperationsClient.deleteOperation`.
    func deleteOperation(request: DeleteOperationRequest) async throws

    /// See `OperationsClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `OperationsClient.cancelOperation`.
    func cancelOperation(request: CancelOperationRequest) async throws

    /// See `OperationsClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `OperationsClient.listOperations`.
    func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `OperationsClient.listOperations`.
    func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Operation, Swift.Error>

    /// See `OperationsClient.getOperation`.
    func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `OperationsClient.deleteOperation`.
    func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `OperationsClient.cancelOperation`.
    func cancelOperation(
      request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.OperationsProtocol {
  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<Operation, Swift.Error> {
    let request = ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
