// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// This resource represents a long-running operation that is the result of a
/// network API call.
public struct Operation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The server-assigned name, which is only unique within the same service that
  /// originally returns it. If you use the default HTTP mapping, the
  /// `name` should be a resource name ending with `operations/{unique_id}`.
  public var name: Swift.String = Swift.String()

  /// Service-specific metadata associated with the operation.  It typically
  /// contains progress information and common metadata such as create time.
  /// Some services might not provide such metadata.  Any method that returns a
  /// long-running operation should document the metadata type, if any.
  public var metadata: GoogleWKT.`Any`? = nil

  /// If the value is `false`, it means the operation is still in progress.
  /// If `true`, the operation is completed, and either `error` or `response` is
  /// available.
  public var done: Swift.Bool = Swift.Bool()

  /// The operation result, which can be either an `error` or a valid `response`.
  /// If `done` == `false`, neither `error` nor `response` is set.
  /// If `done` == `true`, exactly one of `error` or `response` can be set.
  /// Some services might not provide the result.
  public var result: OneOf_Result? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Operation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Operation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let done = CodingKeys(stringValue: "done")
    static let error = CodingKeys(stringValue: "error")
    static let response = CodingKeys(stringValue: "response")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "metadata",
      "done",
      "error",
      "response",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.metadata = try container.decodeIfPresent(GoogleWKT.`Any`.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .done) {
      self.done = value
    }

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
      try resultCheckAndSet(.error(error))
    }
    if let response = try container.decodeIfPresent(GoogleWKT.`Any`?.self, forKey: .response) {
      try resultCheckAndSet(.response(response))
    }
    self.result = result
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.done, forKey: .done)

    if let choice = self.result {
      switch choice {
      case .error(let value):
        try container.encode(value, forKey: .error)
      case .response(let value):
        try container.encode(value, forKey: .response)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The operation result, which can be either an `error` or a valid `response`.
  /// If `done` == `false`, neither `error` nor `response` is set.
  /// If `done` == `true`, exactly one of `error` or `response` can be set.
  /// Some services might not provide the result.
  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// The error result of the operation in case of failure or cancellation.
    indirect case error(GoogleRpc.Status?)
    /// The normal, successful response of the operation.  If the original
    /// method returns no data on success, such as `Delete`, the response is
    /// `google.protobuf.Empty`.  If the original method is standard
    /// `Get`/`Create`/`Update`, the response should be the resource.  For other
    /// methods, the response should have the type `XxxResponse`, where `Xxx`
    /// is the original method name.  For example, if the original method name
    /// is `TakeSnapshot()`, the inferred response type is
    /// `TakeSnapshotResponse`.
    indirect case response(GoogleWKT.`Any`?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.longrunning.Operation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
