// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt
import GoogleRpc

/// This resource represents a long-running operation that is the result of a
/// network API call.
public struct Operation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The server-assigned name, which is only unique within the same service that
  /// originally returns it. If you use the default HTTP mapping, the
  /// `name` should be a resource name ending with `operations/{unique_id}`.
  public var name: String

  /// Service-specific metadata associated with the operation.  It typically
  /// contains progress information and common metadata such as create time.
  /// Some services might not provide such metadata.  Any method that returns a
  /// long-running operation should document the metadata type, if any.
  public var metadata: GoogleCloudWkt.`Any`?

  /// If the value is `false`, it means the operation is still in progress.
  /// If `true`, the operation is completed, and either `error` or `response` is
  /// available.
  public var done: Bool

  /// The operation result, which can be either an `error` or a valid `response`.
  /// If `done` == `false`, neither `error` nor `response` is set.
  /// If `done` == `true`, exactly one of `error` or `response` can be set.
  /// Some services might not provide the result.
  public var result: OneOf_Result?

  /// Initialize a new instance of `Operation`.
  public init(
    name: String = String(),
    metadata: GoogleCloudWkt.`Any`? = nil,
    done: Bool = Bool(),
    result: OneOf_Result? = nil,
  ) {
    self.name = name
    self.metadata = metadata
    self.done = done
    self.result = result
  }

  private enum CodingKeys: String, CodingKey {
    case name = "name"
    case metadata = "metadata"
    case done = "done"
    case error = "error"
    case response = "response"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(String.self, forKey: .name)
    self.metadata = try container.decodeIfPresent(GoogleCloudWkt.`Any`.self, forKey: .metadata)
    self.done = try container.decode(Bool.self, forKey: .done)

    var result: OneOf_Result? = nil
    let resultCheckAndSet = { (value: OneOf_Result) throws in
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = value
    }
    if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
      try resultCheckAndSet(.error(error))
    }
    if let response = try container.decodeIfPresent(GoogleCloudWkt.`Any`?.self, forKey: .response) {
      try resultCheckAndSet(.response(response))
    }
    self.result = result
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.metadata, forKey: .metadata)
    try container.encode(self.done, forKey: .done)

    if let choice = self.result {
      switch choice {
      case .error(let value):
        try container.encode(value, forKey: .error)
      case .response(let value):
        try container.encode(value, forKey: .response)
      }
    }
  }

  /// The operation result, which can be either an `error` or a valid `response`.
  /// If `done` == `false`, neither `error` nor `response` is set.
  /// If `done` == `true`, exactly one of `error` or `response` can be set.
  /// Some services might not provide the result.
  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// The error result of the operation in case of failure or cancellation.
    indirect case error(GoogleRpc.Status?)
    /// The normal, successful response of the operation.  If the original
    /// method returns no data on success, such as `Delete`, the response is
    /// `google.protobuf.Empty`.  If the original method is standard
    /// `Get`/`Create`/`Update`, the response should be the resource.  For other
    /// methods, the response should have the type `XxxResponse`, where `Xxx`
    /// is the original method name.  For example, if the original method name
    /// is `TakeSnapshot()`, the inferred response type is
    /// `TakeSnapshotResponse`.
    indirect case response(GoogleCloudWkt.`Any`?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.longrunning.Operation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
