// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A message representing the message types used by a long-running operation.
///
/// Example:
///
///     rpc Export(ExportRequest) returns (google.longrunning.Operation) {
///       option (google.longrunning.operation_info) = {
///         response_type: "ExportResponse"
///         metadata_type: "ExportMetadata"
///       };
///     }
public struct OperationInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The message name of the primary return type for this
  /// long-running operation.
  /// This type will be used to deserialize the LRO's response.
  ///
  /// If the response is in a different package from the rpc, a fully-qualified
  /// message name must be used (e.g. `google.protobuf.Struct`).
  ///
  /// Note: Altering this value constitutes a breaking change.
  public var responseType: Swift.String = Swift.String()

  /// Required. The message name of the metadata type for this long-running
  /// operation.
  ///
  /// If the response is in a different package from the rpc, a fully-qualified
  /// message name must be used (e.g. `google.protobuf.Struct`).
  ///
  /// Note: Altering this value constitutes a breaking change.
  public var metadataType: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `OperationInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationInfo().with { $0.responseType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let responseType = CodingKeys(stringValue: "responseType")
    static let metadataType = CodingKeys(stringValue: "metadataType")

    static let _knownKeys: Set<Swift.String> = [
      "responseType",
      "metadataType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responseType) {
      self.responseType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .metadataType) {
      self.metadataType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.responseType, forKey: .responseType)
    try container.encode(self.metadataType, forKey: .metadataType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.longrunning.OperationInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
