// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The request message for
/// [Operations.WaitOperation][google.longrunning.Operations.WaitOperation].
///
/// [google.longrunning.Operations.WaitOperation]: <doc:Operations/waitOperation(request:)>
public struct WaitOperationRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the operation resource to wait on.
  public var name: Swift.String

  /// The maximum duration to wait before timing out. If left blank, the wait
  /// will be at most the time permitted by the underlying HTTP/RPC protocol.
  /// If RPC context deadline is also specified, the shorter one will be used.
  public var timeout: GoogleCloudWkt.Duration?

  /// Initialize a new instance of `WaitOperationRequest`.
  public init(
    name: Swift.String = Swift.String(),
    timeout: GoogleCloudWkt.Duration? = nil,
  ) {
    self.name = name
    self.timeout = timeout
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.longrunning.WaitOperationRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
